---
title: "Filter on both PSI14 and PSI89 to get the abundant transcripts"
author: "Anqi Dai"
date: "3/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
library(tidyverse)
```

* Get the PSI for both 14 and 89, as well as control
* Filter on PSI_14 and PSI_89 both > 0.1
* Compute the deltaPSI 
* Filter on abs(deltaPSI) > 0.1
* See the overlap with the sig ones, or see how the sig ones are doing in this.

## sorting out whippet results

```{r}
# get the whippet result that has the PSI A and B in all overlapped locus 
# the significance donesn't matter here since we don't care about the truethness of the delta psi

# find the overlap coord between 14 and 89

w14 <- read_tsv('../../03_ASprofile/data/whippetResult/RF14_vs_cntrl_output.diff')%>%
  dplyr::select(Coord, Type, Psi_A, Psi_B) %>%
  filter(!duplicated(Coord))

w89 <- read_tsv('../../03_ASprofile/data/whippetResult/RF89_vs_cntrl_output.diff')%>%
  dplyr::select(Coord, Type_89 = Type, Psi_A_89 = Psi_A) %>%
  filter(!duplicated(Coord))

ol_locus <- intersect(w14$Coord, w89$Coord)

whi <- w14 %>%
  filter(Coord %in% ol_locus) %>%
  inner_join(w89 %>%
              filter(Coord %in% ol_locus) , by = 'Coord')

# filter out the ones that they have different type
whi <- whi %>%
  filter(Type == Type_89)

# the final table for whippet
final_whippet <- whi %>%
  dplyr::select(locus = Coord, type = Type, Psi_14 = Psi_A, Psi_89 = Psi_A_89, Psi_B = Psi_B) 

# is there any duplicated locus
final_whippet %>%
  filter(duplicated(locus)) %>%
  nrow
```

## sorting out rmats results

```{r}
# now do the above for the rMATS result

# The JCEC.txt files of the AS types
path <- '../../06_rMATS/data/rMATS_result/RF14_control'
fns <- file.path(path, list.files(path, 'JCEC.txt'))

# A3SS 
A3SS <- read_tsv(fns[1]) %>%
  dplyr::select(chr, longExonStart_0base, shortES, geneSymbol, FDR, IncLevel1, IncLevel2) %>%
  rename(start = longExonStart_0base, end = shortES, external_gene_name = geneSymbol, Psi_A = IncLevel1, Psi_B = IncLevel2) %>%
  separate(Psi_A, into = c('Psi_A1','Psi_A2','Psi_A3'), sep = ',', convert = T) %>%
  separate(Psi_B, into = c('Psi_B1','Psi_B2','Psi_B3'), sep = ',', convert = T) %>%
  rowwise() %>%
  mutate(Psi_A = mean(c(Psi_A1, Psi_A2, Psi_A3), na.rm = T),
         Psi_B = mean(c(Psi_B1, Psi_B2, Psi_B3), na.rm = T))  %>%
  mutate(start = start + 1) %>%
  mutate(locus = paste(chr, paste(start,end, sep='-'),sep=':')) %>%
  mutate(tool = 'rMATS',
         type = 'AA') %>%
  dplyr::select(locus, type, Psi_A, Psi_B)

# A5SS 
A5SS <- read_tsv(fns[2]) %>%
  dplyr::select(chr, shortEE, longExonEnd, geneSymbol, FDR, IncLevel1, IncLevel2) %>%
  rename(start = shortEE, end = longExonEnd, external_gene_name = geneSymbol,  Psi_A = IncLevel1, Psi_B = IncLevel2) %>%
  separate(Psi_A, into = c('Psi_A1','Psi_A2','Psi_A3'), sep = ',', convert = T) %>%
  separate(Psi_B, into = c('Psi_B1','Psi_B2','Psi_B3'), sep = ',', convert = T) %>%
  rowwise() %>%
  mutate(Psi_A = mean(c(Psi_A1, Psi_A2, Psi_A3), na.rm = T),
         Psi_B = mean(c(Psi_B1, Psi_B2, Psi_B3), na.rm = T))  %>%
  mutate(locus = paste(chr, paste(start,end, sep='-'),sep=':')) %>%
  mutate(tool = 'rMATS',
         type = 'AD') %>%
  dplyr::select(locus, type, Psi_A, Psi_B)
  
# RI 
RI <- read_tsv(fns[4]) %>%
  dplyr::select(chr, upstreamEE, downstreamES, geneSymbol, FDR, IncLevel1, IncLevel2) %>%
  rename(start = upstreamEE, end = downstreamES, external_gene_name = geneSymbol, Psi_A = IncLevel1, Psi_B = IncLevel2) %>%
  separate(Psi_A, into = c('Psi_A1','Psi_A2','Psi_A3'), sep = ',', convert = T) %>%
  separate(Psi_B, into = c('Psi_B1','Psi_B2','Psi_B3'), sep = ',', convert = T) %>%
  rowwise() %>%
  mutate(Psi_A = mean(c(Psi_A1, Psi_A2, Psi_A3), na.rm = T),
         Psi_B = mean(c(Psi_B1, Psi_B2, Psi_B3), na.rm = T))  %>%
  mutate(locus = paste(chr, paste(start,end, sep='-'),sep=':')) %>%
  mutate(tool = 'rMATS',
         type = 'RI') %>%
  dplyr::select(locus, type, Psi_A, Psi_B)

# SE
SE <-  read_tsv(fns[5]) %>%
  dplyr::select(chr, exonStart_0base, exonEnd, geneSymbol, FDR, IncLevel1, IncLevel2) %>%
  rename(start = exonStart_0base, end = exonEnd, external_gene_name = geneSymbol, Psi_A = IncLevel1, Psi_B = IncLevel2) %>%
  separate(Psi_A, into = c('Psi_A1','Psi_A2','Psi_A3'), sep = ',', convert = T) %>%
  separate(Psi_B, into = c('Psi_B1','Psi_B2','Psi_B3'), sep = ',', convert = T) %>%
  rowwise() %>%
  mutate(Psi_A = mean(c(Psi_A1, Psi_A2, Psi_A3), na.rm = T),
         Psi_B = mean(c(Psi_B1, Psi_B2, Psi_B3), na.rm = T))  %>%
  mutate(start = start + 1) %>%
  mutate(locus = paste(chr, paste(start,end, sep='-'),sep=':')) %>%
  mutate(tool = 'rMATS',
         type = 'CE') %>%
  dplyr::select(locus, type, Psi_A, Psi_B)

# MXE
MXE <- read_tsv(fns[3]) %>%
  dplyr::select(chr, upstreamES, downstreamEE, geneSymbol, FDR, IncLevel1, IncLevel2) %>%
  rename(start = upstreamES, end = downstreamEE, external_gene_name = geneSymbol, Psi_A = IncLevel1, Psi_B = IncLevel2) %>%
  separate(Psi_A, into = c('Psi_A1','Psi_A2','Psi_A3'), sep = ',', convert = T) %>%
  separate(Psi_B, into = c('Psi_B1','Psi_B2','Psi_B3'), sep = ',', convert = T) %>%
  rowwise() %>%
  mutate(Psi_A = mean(c(Psi_A1, Psi_A2, Psi_A3), na.rm = T),
         Psi_B = mean(c(Psi_B1, Psi_B2, Psi_B3), na.rm = T))  %>%
  mutate(locus = paste(chr, paste(start,end, sep='-'),sep=':')) %>%
  mutate(tool = 'rMATS',
         type = 'MXE') %>%
  dplyr::select(locus, type, Psi_A, Psi_B)




# combine them together
df14 <- bind_rows(A3SS, A5SS, RI, SE, MXE) %>%
  distinct(locus, .keep_all = TRUE)

```



```{r}
# The JCEC.txt files of the AS types
path <- '../../06_rMATS/data/rMATS_result/RF89_control'
fns <- file.path(path, list.files(path, 'JCEC.txt'))

# A3SS 
A3SS <- read_tsv(fns[1]) %>%
  dplyr::select(chr, longExonStart_0base, shortES, geneSymbol, FDR, IncLevel1, IncLevel2) %>%
  rename(start = longExonStart_0base, end = shortES, external_gene_name = geneSymbol, Psi_A = IncLevel1, Psi_B = IncLevel2) %>%
  separate(Psi_A, into = c('Psi_A1','Psi_A2','Psi_A3'), sep = ',', convert = T) %>%
  separate(Psi_B, into = c('Psi_B1','Psi_B2','Psi_B3'), sep = ',', convert = T) %>%
  rowwise() %>%
  mutate(Psi_A = mean(c(Psi_A1, Psi_A2, Psi_A3), na.rm = T),
         Psi_B = mean(c(Psi_B1, Psi_B2, Psi_B3), na.rm = T))  %>%
  mutate(start = start + 1) %>%
  mutate(locus = paste(chr, paste(start,end, sep='-'),sep=':')) %>%
  mutate(tool = 'rMATS',
         type = 'AA') %>%
  dplyr::select(locus, type, Psi_A, Psi_B)

# A5SS 
A5SS <- read_tsv(fns[2]) %>%
  dplyr::select(chr, shortEE, longExonEnd, geneSymbol, FDR, IncLevel1, IncLevel2) %>%
  rename(start = shortEE, end = longExonEnd, external_gene_name = geneSymbol,  Psi_A = IncLevel1, Psi_B = IncLevel2) %>%
  separate(Psi_A, into = c('Psi_A1','Psi_A2','Psi_A3'), sep = ',', convert = T) %>%
  separate(Psi_B, into = c('Psi_B1','Psi_B2','Psi_B3'), sep = ',', convert = T) %>%
  rowwise() %>%
  mutate(Psi_A = mean(c(Psi_A1, Psi_A2, Psi_A3), na.rm = T),
         Psi_B = mean(c(Psi_B1, Psi_B2, Psi_B3), na.rm = T))  %>%
  mutate(locus = paste(chr, paste(start,end, sep='-'),sep=':')) %>%
  mutate(tool = 'rMATS',
         type = 'AD') %>%
  dplyr::select(locus, type, Psi_A, Psi_B)
  
# RI 
RI <- read_tsv(fns[4]) %>%
  dplyr::select(chr, upstreamEE, downstreamES, geneSymbol, FDR, IncLevel1, IncLevel2) %>%
  rename(start = upstreamEE, end = downstreamES, external_gene_name = geneSymbol, Psi_A = IncLevel1, Psi_B = IncLevel2) %>%
  separate(Psi_A, into = c('Psi_A1','Psi_A2','Psi_A3'), sep = ',', convert = T) %>%
  separate(Psi_B, into = c('Psi_B1','Psi_B2','Psi_B3'), sep = ',', convert = T) %>%
  rowwise() %>%
  mutate(Psi_A = mean(c(Psi_A1, Psi_A2, Psi_A3), na.rm = T),
         Psi_B = mean(c(Psi_B1, Psi_B2, Psi_B3), na.rm = T))  %>%
  mutate(locus = paste(chr, paste(start,end, sep='-'),sep=':')) %>%
  mutate(tool = 'rMATS',
         type = 'RI') %>%
  dplyr::select(locus, type, Psi_A, Psi_B)

# SE
SE <-  read_tsv(fns[5]) %>%
  dplyr::select(chr, exonStart_0base, exonEnd, geneSymbol, FDR, IncLevel1, IncLevel2) %>%
  rename(start = exonStart_0base, end = exonEnd, external_gene_name = geneSymbol, Psi_A = IncLevel1, Psi_B = IncLevel2) %>%
  separate(Psi_A, into = c('Psi_A1','Psi_A2','Psi_A3'), sep = ',', convert = T) %>%
  separate(Psi_B, into = c('Psi_B1','Psi_B2','Psi_B3'), sep = ',', convert = T) %>%
  rowwise() %>%
  mutate(Psi_A = mean(c(Psi_A1, Psi_A2, Psi_A3), na.rm = T),
         Psi_B = mean(c(Psi_B1, Psi_B2, Psi_B3), na.rm = T))  %>%
  mutate(start = start + 1) %>%
  mutate(locus = paste(chr, paste(start,end, sep='-'),sep=':')) %>%
  mutate(tool = 'rMATS',
         type = 'CE') %>%
  dplyr::select(locus, type, Psi_A, Psi_B)

# MXE
MXE <- read_tsv(fns[3]) %>%
  dplyr::select(chr, upstreamES, downstreamEE, geneSymbol, FDR, IncLevel1, IncLevel2) %>%
  rename(start = upstreamES, end = downstreamEE, external_gene_name = geneSymbol, Psi_A = IncLevel1, Psi_B = IncLevel2) %>%
  separate(Psi_A, into = c('Psi_A1','Psi_A2','Psi_A3'), sep = ',', convert = T) %>%
  separate(Psi_B, into = c('Psi_B1','Psi_B2','Psi_B3'), sep = ',', convert = T) %>%
  rowwise() %>%
  mutate(Psi_A = mean(c(Psi_A1, Psi_A2, Psi_A3), na.rm = T),
         Psi_B = mean(c(Psi_B1, Psi_B2, Psi_B3), na.rm = T))  %>%
  mutate(locus = paste(chr, paste(start,end, sep='-'),sep=':')) %>%
  mutate(tool = 'rMATS',
         type = 'MXE') %>%
  dplyr::select(locus, type, Psi_A, Psi_B)





# combine them together
df89 <- bind_rows(A3SS, A5SS, RI, SE, MXE) %>%
  distinct(locus, .keep_all = TRUE) %>%
  dplyr::select(locus, type_89 = type, Psi_A_89 = Psi_A, Psi_B_89 = Psi_B)
```



```{r}
# get the final result for rmats
ol_locus <- intersect(df14$locus, df89$locus)

rmats <- df14 %>%
  inner_join(df89, by  = 'locus') %>%
  filter(type == type_89) %>%
  rowwise() %>%
  mutate(Psi_B = mean(c(Psi_B, Psi_B_89), na.rm = T)) %>%
  dplyr::select(locus, type, Psi_14 = Psi_A, Psi_89 = Psi_A_89, Psi_B)


```

## deduplicate between rmats and whippet

```{r}
# wow this distinct function is lightning fast!!!!!
two <- bind_rows(final_whippet, rmats ) %>%
  distinct(locus, .keep_all = T)
  
```

## sorting out the IRfinder results

```{r}

IR14 <- read_tsv('../../05_IRfinder/data/rawIRfinderResult/RF14_vs_ctrl.txt', comment = '#')  %>%
  rename_all( funs(stringr::str_replace_all(., '-', '_'))) %>%
  mutate(type = 'RI')  %>%
  dplyr::select(Chr, Start, End, type, A_IRratio, B_IRratio) %>%
  mutate(Start = Start + 1) %>%
  mutate(locus = paste(Chr, paste(Start, End, sep = '-'), sep = ':')) %>%
  dplyr::select(type:locus) %>%
  filter(!duplicated(locus)) %>%
  rename(Psi_A = A_IRratio, Psi_B = B_IRratio)
 

IR89 <- read_tsv('../../05_IRfinder/data/rawIRfinderResult/RF89_vs_ctrl.txt', comment = '#')  %>%
  rename_all( funs(stringr::str_replace_all(., '-', '_'))) %>%
  mutate(type = 'RI')  %>%
  dplyr::select(Chr, Start, End, type, A_IRratio, B_IRratio)  %>%
  mutate(Start = Start + 1) %>%
  mutate(locus = paste(Chr, paste(Start, End, sep = '-'), sep = ':')) %>%
  filter(!duplicated(locus)) %>%
  dplyr::select(locus, type_89 = type, Psi_A_89 = A_IRratio, Psi_B_89 = B_IRratio)
  
```

```{r}
# join them together

IRfinder <- IR14 %>%
  inner_join(IR89, by  = 'locus') %>%
  dplyr::select(locus, type, Psi_14 = Psi_A, Psi_89 = Psi_A_89, Psi_B) 

```

## deduplicate between IRfinder and the other 2

```{r}
final <- bind_rows(IRfinder, two  ) %>%
  distinct(locus, .keep_all = T)
```

```{r}
# write out the final data
write_csv(final, '../output/all_three_PSI_14_and_89_and_control_not_filtered.csv')
```

