'''
This snakefile will do the following:
Use IFfinder to identify the differentially retend introns when comparing KD vs control

* Build reference for IRfinder
* Map the reads to the reference and produce the bam file
* Concat the unsorted bam file
* Analyze using analysisWithLowReplicates.pl  
'''

from glob import glob
import os

# -----------------------------------------------------------

sample_dir = '/restricted/projectnb/flynngrp/adai/Day3_SDE2'

sample_names = json.load(open('../samples.json')).keys()

IRfinder_path = '../../../05_IRfinder/IRfinder_software/IRFinder-1.2.5/bin/IRFinder'
Ref_dir = '../../../05_IRfinder/REF/Human-hg38'

# -----------------------------------------------------------

rule output:
    input:

rule pooled_14:
    input:
        bam='{sample_dir}/IRfinder_result/RF14_concat3_unsorted.bam',
        ref=Ref_dir,
        IRpath=IRfinder_path 
    output:
        '{sample_dir}/IRfinder_result/Pooled_14/IRFinder-IR-dir.txt'
    threads:
        12
    params:
        prefix='{sample_dir}/IRfinder_result/Pooled_14/'
    shell:
        '''
        export LD_LIBRARY_PATH=/projectnb/bubhub/conda_root/user_conda/adai/envs/flynn_altstatus/lib;
        {input.IRpath} -m BAM -r {input.ref} -d  {params.prefix} {input.bam} > {output}
        '''    


rule pooled_89:
    input:
        bam='{sample_dir}/IRfinder_result/RF89_concat3_unsorted.bam',
        ref=Ref_dir,
        IRpath=IRfinder_path 
    output:
        '{sample_dir}/IRfinder_result/Pooled_89/IRFinder-IR-dir.txt'
    threads:
        12
    params:
        prefix='{sample_dir}/IRfinder_result/Pooled_89/'
    shell:
        '''
        export LD_LIBRARY_PATH=/projectnb/bubhub/conda_root/user_conda/adai/envs/flynn_altstatus/lib;
        {input.IRpath} -m BAM -r {input.ref} -d  {params.prefix} {input.bam} > {output}
        '''    


rule pooled_ctrl:
    input:
        bam='{sample_dir}/IRfinder_result/RFctrl_concat3_unsorted.bam',
        ref=Ref_dir,
        IRpath=IRfinder_path 
    output:
        '{sample_dir}/IRfinder_result/Pooled_ctrl/IRFinder-IR-dir.txt'
    threads:
        12
    params:
        prefix='{sample_dir}/IRfinder_result/Pooled_ctrl/'
    shell:
        '''
        export LD_LIBRARY_PATH=/projectnb/bubhub/conda_root/user_conda/adai/envs/flynn_altstatus/lib;
        {input.IRpath} -m BAM -r {input.ref} -d  {params.prefix} {input.bam} > {output}
        '''    

# Calling the comparison script to get the differential IR results

rule compare_IR_14vsctrl:
    input:
        pooled_14='{sample_dir}/IRfinder_result/Pooled_14/IRFinder-IR-dir.txt',
        pooled_ctrl='{sample_dir}/IRfinder_result/Pooled_ctrl/IRFinder-IR-dir.txt',
        RF14_1='{sample_dir}/IRfinder_result/RF-3-14-1/IRFinder-IR-dir.txt',
        RF14_2='{sample_dir}/IRfinder_result/RF-3-14-2/IRFinder-IR-dir.txt',
        RF14_3='{sample_dir}/IRfinder_result/RF-3-14-3/IRFinder-IR-dir.txt',
        c1='{sample_dir}/IRfinder_result/RF-3-M-1/IRFinder-IR-dir.txt',
        c2='{sample_dir}/IRfinder_result/RF-3-M-2/IRFinder-IR-dir.txt',
        c3='{sample_dir}/IRfinder_result/RF-3-M-3/IRFinder-IR-dir.txt'
    output:
        '{sample_dir}/IRfinder_result/RF14_vs_ctrl.txt'
    shell:
        '''
        ../../../05_IRfinder/IRfinder_software/IRFinder-1.2.5/bin/analysisWithLowReplicates.pl  \
            -A {input.pooled_14} {input.RF14_1} {input.RF14_2} {input.RF14_3}  \
            -B {input.pooled_ctrl} {input.c1} {input.c2}  {input.c3} > {output}
        '''


rule compare_IR_89vsctrl:
    input:
        pooled_89='{sample_dir}/IRfinder_result/Pooled_89/IRFinder-IR-dir.txt',
        pooled_ctrl='{sample_dir}/IRfinder_result/Pooled_ctrl/IRFinder-IR-dir.txt',
        RF89_1='{sample_dir}/IRfinder_result/RF-3-89-1/IRFinder-IR-dir.txt',
        RF89_2='{sample_dir}/IRfinder_result/RF-3-89-2/IRFinder-IR-dir.txt',
        RF89_3='{sample_dir}/IRfinder_result/RF-3-89-3/IRFinder-IR-dir.txt',
        c1='{sample_dir}/IRfinder_result/RF-3-M-1/IRFinder-IR-dir.txt',
        c2='{sample_dir}/IRfinder_result/RF-3-M-2/IRFinder-IR-dir.txt',
        c3='{sample_dir}/IRfinder_result/RF-3-M-3/IRFinder-IR-dir.txt'
    output:
        '{sample_dir}/IRfinder_result/RF89_vs_ctrl.txt'
    shell:
        '''
        ../../../05_IRfinder/IRfinder_software/IRFinder-1.2.5/bin/analysisWithLowReplicates.pl  \
            -A {input.pooled_89} {input.RF89_1} {input.RF89_2} {input.RF89_3}  \
            -B {input.pooled_ctrl} {input.c1} {input.c2}  {input.c3}  > {output}
        '''


