---
title: "04_Fig4"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
library(tidyverse)
library(ggpubr)
library(scales)
library(extrafont)
library(grid)
library(cowplot)
```

```{r}
# load the result table
res <- read_csv('../../05_IRfinder/data/02_intersect_sig_and_intersect_non_sig_all_other_info.csv')
```


# SiSDE2-1 (Si14 only)

```{r}
table(res$Significance)
```

```{r}
# parameters about the size of the text and the axis text(for publication level of plots)
axis_text_size <- 9
general_text_size <- 10
rotation_angle <- 30
our_font <- 'Arial'
```

## a: SDE2 IR events VS IRfinder events

```{r}
# make the 14 89 named si-1 and si-2
compare <- read_csv('../output/paper and our KD events compare.csv') %>%
  mutate(gene = str_replace(gene, ' RF14', '-1'),
         gene = str_replace(gene, ' RF89', '-2')) %>% 
  mutate(gene = if_else(str_detect(gene, 'SDE2'),
                        str_glue('si{gene}'),
                        gene))

compare_plot <- compare %>%
  mutate(gene = str_replace(gene, 'RF', 'Si'))  %>%
  mutate(group = if_else(str_detect(gene, 'SDE2'), ' SDE2 data', ' IRfinder paper  ')) %>%
  ggbarplot(x = 'gene', y ='increased',
            color = 'group', fill = 'group',
            ylab = 'Number of events')  +
  ylim(0, 6800) +
  geom_text(aes(label = increased_in_perc), vjust = -1, size = 2 ) +
  scale_color_manual(values = c('#EEBF2B', '#1175C0'))  +
  scale_fill_manual(values = c('#EEBF2B', '#1175C0'))  +
  theme(text = element_text(family = our_font),
        axis.text.x = element_text(angle = rotation_angle, hjust = 1),
        axis.text=element_text(size=axis_text_size),
        axis.title.x=element_blank(),
        axis.title.y=element_text(size = general_text_size),
        legend.title = element_blank())
```

## b: Position

```{r}
pos <- res %>%
  gghistogram(x = 'RI_prop',
              palette = 'lancet',
              color = 'white', fill = 'Significance', 
              bins = 40,
              add = "median",
              xlab = 'RI position') + 
  theme(text = element_text(family = our_font),
        axis.text=element_text(size=axis_text_size),
        axis.title=element_text(size = general_text_size))
```

## c: Length
 
```{r}
# add a third box which is all the background introns other than the first two
# load the background introns
bg <- read_csv('../data/unique_introns_for_expressive_genes.csv') %>%
  filter(intronLen > 30)

# 
IRfinder <- res %>%
    dplyr::select(ensembl_gene_id, locus, Significance, RI_len)


all <- bind_rows(
  bg %>%
    filter(!locus %in% IRfinder$locus) %>%
    mutate(Significance = 'Non-AS') %>%
    dplyr::select(Significance, RI_len = intronLen),
  IRfinder %>%
    dplyr::select(Significance, RI_len)
) %>%
  mutate(Significance = factor(Significance, levels = c('Sig','Non-sig','Non-AS')))


# wanna add a label of how many events in each type of Significance
tally <- table(all$Significance) %>%
  data.frame %>%
  dplyr::rename(Significance = names(.)[1])

all <- all %>%
  split(.$Significance) %>%
  map_df(~  mutate(.data = ., Num = nrow(.)))

# annotation_height to be the min of the Non-AS
annotation_height <- all %>%
  filter(Significance == 'Non-AS') %>%
  summarise(mini = min(RI_len))%>%
  unlist

len <- all %>%
  ggboxplot(x = "Significance", y = 'RI_len',  color = 'Significance',
            ylab = 'Length of retained intron', xlab = '',
            palette = 'lancet') +
  scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x),
              labels = trans_format("log10", math_format(10^.x)))  +
  annotation_logticks(sides = "l")  +
  scale_color_manual(values = c('#EC0000','#00468B', '#374E54'))  +
  stat_compare_means(comparisons = list(c('Sig', 'Non-sig'),
                                        c('Non-sig','Non-AS'),
                                        c('Sig','Non-AS')),
                     label = "p.signif") +
  geom_text(data = tally, aes(x = Significance, y = annotation_height, label = Freq)) +
  theme(text = element_text(family = our_font),
        axis.text=element_text(size=axis_text_size),
        axis.title.y=element_text(size = general_text_size),
        legend.position="none")
```


## d: GC content

```{r}
# change the format of the res sig table in the above way
IRfinder <- res %>% 
  dplyr::select(locus,
                intronLen = RI_len,
                category = Significance,
                GC_per,
                ss5_score,
                ss3_score)

# load the data from the non-as in the background
non_AS <- read_csv('../../05_IRfinder/data/03_non_AS_seq_info.csv') %>% 
  filter(!locus %in% IRfinder$locus)

# bind them together
all <- bind_rows(
  IRfinder,
  non_AS
)

```


```{r}
gc <- all %>%
    ggboxplot(x = 'category', y = 'GC_per',
              palette = 'lancet',
              color = 'category', 
              xlab = 'GC% ',
              ylab = 'GC%') +
    scale_y_continuous(breaks=seq(0, 100, 25)) +
    stat_compare_means(comparisons = list(c('Sig', 'Non-sig'),
                                          c('Non-AS-short','Non-AS-long'),
                                          c('Sig','Non-AS-short')), label = "p.signif")+   
    scale_color_manual(values = c( '#EC0000','#00468B','#42B440','#1799B1')) +
    theme(text = element_text(family = our_font),
        legend.position="none",
        axis.title.x=element_blank(),
        axis.text=element_text(size=axis_text_size),
        axis.title.y=element_text(size = general_text_size)) 
  
```

## e: Splice site strength 

```{r}
strength <- all %>%
  dplyr::select(locus, category, ss5_score, ss3_score) %>%
  ggboxplot(x = 'category', y = c('ss5_score','ss3_score'),combine = T,
            ylab = 'Splice site score', xlab = '',
            palette = 'lancet', color = 'category')   +
  scale_y_continuous(limits = c(-10, 25)) +
  stat_compare_means(comparisons = list(c('Sig', 'Non-sig'),
                                        c('Non-AS-short','Non-AS-long'),
                                        c('Sig','Non-AS-short')), 
                     label = "p.signif",
                     label.y = c(18, 20, 24)) +   
  scale_color_manual(values = c( '#EC0000','#00468B','#42B440','#1799B1')) +
  theme(text = element_text(family = our_font),  
        axis.text=element_text(size=axis_text_size),
        axis.text.x = element_text(angle = rotation_angle, hjust = 1),
        axis.title.y=element_text(size = general_text_size),
        legend.position="none") + 
  ggsave('../figs/the score.jpg', width = 8, height = 6)
```

## f: GSEA 

```{r}
# the gsea of the significant genes
res %>%
  filter(Significance == 'Sig') %>%
  distinct(ensembl_gene_id)  %>%
  write_csv('../data/unique_gene_id_for_significant_day3.csv', col_names = F)

# plot the -log10(q) value from Metascape results (top 10)
gsea <- read_csv('../output/Metascape/day3_sig_gene/all/Enrichment_GO/GO_AllLists.csv') %>%
  top_n(n = -10, wt = `Log(q-value)`) %>%
  mutate(neg_log_q = abs(`Log(q-value)`)) %>%
  mutate(Description = str_replace(Description, ' \\(..+$',''))  %>% 
  mutate(Description = if_else(str_detect(Description, 'precursor'),
                               'Biosynthesis of the\nN-glycan precursor',
                               Description)) %>% 
    mutate(Description = if_else(str_detect(Description, 'cellular protein catabolic process'),
                               'cellular protein\ncatabolic process',
                               Description)) 

gsea_plot <- gsea %>%
  ggbarplot(x = 'Description', y = 'neg_log_q',
            xlab = '', ylab = '-log10(q)',
            color = 'white', fill = '#00468B') +
  coord_flip() +
  theme(text = element_text(family = our_font),  
        axis.text.x=element_text(size=axis_text_size),
        axis.title.x=element_text(size = general_text_size),
        axis.text.y = element_text(size = 8),
        legend.position="none") 

```  

## Assemble

```{r}
g <- plot_grid(compare_plot, pos, len, gc, strength, gsea_plot,  
          nrow = 3, 
          align = 'hv',
          labels = 'AUTO',
          axis = 'b')  +
  ggsave('../figs/d3_Assembled_fig4_intersection.jpg', width = 8, height = 12, dpi = 300)
```


# Side note

```{r}
# get two numbers from Non-AS box, differentiate them to be long and short
# short being shorter than the 75 percentile of the sig ones len
# let me see if I can do that in a single pipe
ret <- all %>%
  split(.$Significance) %>%
  map_df(~ mutate(.data = ., qt75 = quantile(RI_len, 0.75)))

sig75 <- ret %>%
  filter(Significance == 'Sig') %>%
  distinct(qt75) %>%
  unlist
  
ret %>%
  filter(Significance == 'Non-AS')  %>%
  mutate(category = if_else(RI_len < sig75, 'short','long')) %>%
  group_by(category) %>%
  summarise(num = n()) %>%
  kable(caption = 'Short(< 75% of the sig ones) and long introns in Non-AS') %>%
  kable_styling(full_width = F)
```

```{r}
# genes in the top 10 pathways in the GSEA
top10 <-  read_csv('../output/Metascape/day3_sig_gene/all/Enrichment_GO/GO_AllLists.csv') %>%
  top_n(n = -10, wt = `Log(q-value)`) 


top10 %>%
  write_csv('../output/top10_enriched_pathways_day3_sig_genes.csv')
```

