---
title: "The metadata of the ENCODE samples"
author: "Anqi Dai"
date: "5/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
library(tidyverse)
library(kableExtra)
```

```{r}
# load the metadata file for fastq
meta <- read_tsv('../data/metadata.tsv') 

# to generate the whole mv command so that I can run in bash script later`
# the new file name has to be in a certain way so that later parsing the sample name will be easy
output <- meta %>%
  rename_all(funs(stringr::str_replace_all(., ' |\\(|\\)', '_') )) %>%
  dplyr::select(accession = File_accession, 
                target = Experiment_target, 
                bioreplicate = Biological_replicate_s_, 
                paired_end = Paired_end) %>%
  mutate(target = str_replace(target, '-human',''),
         new_fn = str_glue('{target}-rep{bioreplicate}_R{paired_end}.fastq.gz'),
         old_fn = str_glue('{accession}.fastq.gz'))  %>%
  mutate(command = str_glue('mv {old_fn} {new_fn}'),
         now_fn = str_glue('KD_{target}_rep_{bioreplicate}_R{paired_end}.fastq.gz'),
         new_command = str_glue('mv {now_fn} {new_fn}'))
 
output %>%
  dplyr::select(new_command) %>% 
  write.table('../data/renaming_encode_fastq_files.txt', quote = F, col.names = F, row.names = F)
```

```{r}
# ahhhh the control samples also from the ENCODE
ctrl <- read_tsv('../data/control_meta.tsv') 

ctrl_output <- ctrl %>%
  rename_all(funs(stringr::str_replace_all(., ' |\\(|\\)', '_') )) %>%
  dplyr::select(accession = File_accession, 
                bioreplicate = Biological_replicate_s_, 
                paired_end = Paired_end,
                paired_with = Paired_with) %>% 
  mutate(group = 'ctrl',
         suppliment = c('1','1','','','2','2'),
         replicate = str_glue('{bioreplicate}{suppliment}'),
         new_fn = str_glue('{group}-rep{replicate}_R{paired_end}.fastq.gz'),
         old_fn = str_glue('{accession}.fastq.gz'),
         command = str_glue('mv {old_fn} {new_fn}')) 
  
ctrl_output %>%
  dplyr::select(command) %>% 
  write.table('../data/renaming_encode_control_fastq_files.txt', quote = F, col.names = F, row.names = F)
```



