---
title: "Fetching the sequence for AS and non AS"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
library(tidyverse)
library(GenomicRanges)
library(BSgenome)
library(BSgenome.Hsapiens.NCBI.GRCh38)
library(seqinr)
require(ggseqlogo)
require(ggplot2)
```

```{r}
# load the seq table
as_seq <- read_csv('../data/as_RI_seq_coord.csv') %>%
  mutate(chr = str_replace_all(chr, 'chr',''))

no_seq <- read_csv('../data/no_as_RI_seq_coord.csv')%>%
  mutate(chr = str_replace_all(chr, 'chr',''))
```

```{r}
# get the actual sequence in a function 
genome <- BSgenome.Hsapiens.NCBI.GRCh38 

get_seq_function <- function(df) {
  
  grange5 <-  makeGRangesFromDataFrame(df, 
                                     seqnames.field=c("chr"),  
                                     start.field="ss5_start", 
                                     end.field=c("ss5_end"), 
                                     strand.field="direction")


  grange3 <-  makeGRangesFromDataFrame(df, 
                                       seqnames.field=c("chr"),  
                                       start.field="ss3_start", 
                                       end.field=c("ss3_end"), 
                                       strand.field="direction")
  
  ret <- df %>%
    mutate(ss5_seq = as.character(BSgenome::getSeq(genome, grange5)),
           ss3_seq = as.character(BSgenome::getSeq(genome, grange3)) )
  return(ret)
}

```

```{r}
all <- list(as_seq %>%
              mutate(status = 'AS'), 
            NONAS = no_seq %>%
              mutate(status = 'NO')) %>%
  map_dfr(., ~ get_seq_function(.)) 

final <- all %>%
  dplyr::select(status, ss5_seq, ss3_seq) %>%
  gather(key = group, value = seq, ... = ss5_seq: ss3_seq ) %>%
  unite(col = Group, ... = status:group, sep = '_')
```

```{r}
# use the ggseqlogo pkg to plot the logo
final %>%
  split(.$Group) %>%
  map(~ ggplot() + 
        geom_logo( .$seq ) + 
        theme_logo() + 
        labs(title = str_glue('{.$Group} logo'))+
        theme_classic() +
        theme(
              text = element_text(size=25),
              axis.text.x = element_text(angle = 90, hjust = 1, size = 15))+
        ggsave(str_glue('../figs/{.$Group} logo.pdf'),device = 'pdf', width = 18, height = 10, dpi = 300))


```

