---
title: "06 relax Whippet to 0.25"
author: "Anqi Dai"
date: "3/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(biomaRt)
```

Relax Whippet to 0.25 threshold and get a table of the significant locus with tool, type and gene name information.

```{r}
################################################################################
# THE WHIPPET SIG GENES (absDeltaPsi > 0.1 & **Probability > 0.8** & Psi_A > 0.1)
################################################################################

RF14.ctrl <- read_tsv('../../03_ASprofile/data/whippetResult/RF14_vs_cntrl_output.diff') %>%
  mutate(absDeltaPsi = abs(DeltaPsi)) %>%
  mutate(Gene = str_replace_all(string = Gene, pattern = '\\..+$', replacement = '')) %>%
  mutate(Group = 'RF14.ctrl')  %>%
  filter(absDeltaPsi > 0.1 & Probability > 0.8 & Psi_A > 0.1)  %>%
  mutate(tool = 'Whippet') %>%
  dplyr::select(locus = Coord, tool, type = Type, GeneID = Gene)


RF89.ctrl <- read_tsv('../../03_ASprofile/data/whippetResult/RF89_vs_cntrl_output.diff') %>%
  mutate(absDeltaPsi = abs(DeltaPsi)) %>%
  mutate(Gene = str_replace_all(string = Gene, pattern = '\\..+$', replacement = '')) %>%
  mutate(Group = 'RF89.ctrl')  %>%
  filter(absDeltaPsi > 0.1 & Probability > 0.8 & Psi_A > 0.1) %>%
  dplyr::select(locus = Coord)

overlap_whippet  <-  RF14.ctrl %>%
  inner_join(RF89.ctrl , by = 'locus')


# get the gene name for the table
mart <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")

# the ensembl_gene_id of the genes that you are interested in 
genes <- overlap_whippet$GeneID

# retrieve the feature information of the listed attributes
symbol <- getBM(filters = "ensembl_gene_id",
                attributes = c('ensembl_gene_id','external_gene_name'),
                values = genes, 
                mart = mart)
# add the gene name to the table
Overlap_whippet <- overlap_whippet %>%
  left_join(symbol %>%
              rename(GeneID = ensembl_gene_id), by = 'GeneID') %>%
  dplyr::select(-GeneID)

# how many records are there 
nrow(Overlap_whippet)

# write out the table
write_csv(Overlap_whippet, '../output/FDR025_Whippet_results.csv')
```

