---
title: "07 relax IRfinder to 0.25"
author: "Anqi Dai"
date: "3/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F) 
```


```{r}
################################################################################
# THE IRFINDER SIG GENES (FDR < 0.25)
################################################################################

data_path <- '../../05_IRfinder/data/rawIRfinderResult'
fns <- file.path(data_path, list.files(data_path, pattern = 'txt'))

# format the table like below (generate the locus ID, change the colnames, format the geneID string, separate that one column to three, generate the padj value.)
raw_df_list <- lapply(fns, function(fn){
  res = read_tsv(fn,comment = '#',col_names = T) %>%
    mutate(Locus =paste(Chr,paste(Start, End, sep = '-'), sep = ':' ) ) 
  
  colnames(res) <- colnames(res) %>%
    gsub('-', '_', .)
  
  res = res %>%
    separate('Intron_GeneName/GeneID', into = c('Symbol', 'GeneID', 'Category'), sep = '/') %>%
    # get rid of the . and digits after that in GeneID
    mutate(GeneID = str_replace_all(string = GeneID, pattern = '\\..*$', replacement = '')) %>%
    mutate(padj = p.adjust(p_diff, method = 'BH')) 
})

##################################################################################

# filter the result like below:
# * Remove records marked with "known-exon". 
# * Remove records marked with "MinorIsoform" either in experiment or control. 
# * Adjust the P-value with BH method 
# * Select the records with padj < 0.25

true_df_list <- lapply(raw_df_list, function(df) {
  res = df  %>%
    filter(! Category == 'known-exon') %>%
    filter( A_IRok != 'MinorIsoform' &  B_IRok != 'MinorIsoform' ) %>%
    filter(padj < 0.25) 
  return(res)
} )

false_df_list <- lapply(raw_df_list, function(df) {
  res = df  %>%
    filter(! Category == 'known-exon') %>%
    filter( A_IRok != 'MinorIsoform' &  B_IRok != 'MinorIsoform' ) %>%
    filter(padj >= 0.25) 
  return(res)
} )

##################################################################################

# TRUE: sig in both
# FALSE: sig in neither but overlapped in both

true_locus <- intersect(true_df_list[[1]]$Locus, true_df_list[[2]]$Locus)
false_locus <- intersect(false_df_list[[1]]$Locus, false_df_list[[2]]$Locus)

# subset the df to include only the true and false locus

subset_df_list <- lapply(raw_df_list, function(df){
  res = df %>%
    filter(Locus %in% true_locus) 
})

overlap_IRfinder <- subset_df_list[[1]] %>%
  mutate(tool = 'IRfinder',
         type = "RI") %>%
  dplyr::select(locus = Locus, tool, type, external_gene_name = Symbol)



# correct the IRfinder start position
Overlap_IRfinder <- overlap_IRfinder %>%
  separate(locus, into = c('chr','coord'), sep = ':') %>%
  separate(coord, into = c('start', 'end'), sep = '-', convert = T) %>%
  mutate(start = start + 1) %>%
  mutate(locus = paste(chr, paste(start,end, sep='-'),sep=':'))  %>%
  dplyr::select(locus, tool, type, external_gene_name)

# how many records are there
nrow(Overlap_IRfinder)


# write out the table
write_csv(Overlap_IRfinder, '../output/FDR025_IRfinder_results.csv')
```

