'''
This Snakefile will do:
* DE between pooled KD and control
* annotate the DE result with gene name
'''

rule DE:
    input:
        pheno='data/pheno_pooled_KD.csv',
        cts='../10_norval_annotation_quantification/data/normal_quant_salmon_raw_cts_filtered.csv'
    output:
        'output/03_pooledKD_DE.tsv'
    shell:
        'detk-de deseq2 "counts ~ Status" {input.cts} {input.pheno} > {output}'

rule download_gtf:
    output:
        'homo_sapiens_grch38.json'
    shell:
        '''
        piomart  gtf -u --species homo_sapiens --release release-93 --output homo_sapiens_grch38.gtf \
        && piomart json -f homo_sapiens_grch38.gtf -o {output[0]}
        '''

rule annotated_deseq_results:
    input:
        'homo_sapiens_grch38.json',
        'output/03_pooledKD_DE.tsv'
    output:
        'output/03_pooledKD_DE_annotated.csv'
    shell:
        '''
        piomart dataframe {input[1]} --offline -f {input[0]} --columns=gene_name --output={output[0]}
        '''
