---
title: "Draw the FDR005 pie chart"
author: "Anqi Dai"
date: "5/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
library(tidyverse)
library(RColorBrewer)
library(cowplot)
library(ggpubr)
```

```{r}
# load the data 
final <- read_csv('../../16_THE_PSI/output/day3_sig_events_all_tools_not_filtered_by_PSI.csv')
```

```{r}
# my general settings
axis_text_size <- 9
general_text_size <- 10
```

```{r}
# get the data in table right
hex <- c(brewer.pal(n = 8, name = "Dark2"), '#00468B')
hex <- c( "#D95F02", "#7570B3", "#E7298A", "#66A61E", "#E6AB02", "#A6761D", "#666666","#1B9E77", "#00468B")
  
colorPal <- data_frame(
  type = c('AD','TS','MXE','RI','AF','CE','AA','AL','TE'), 
  color = hex) 

res <- final %>%
          group_by(type) %>%
          summarise(count = n())%>%
          mutate(perc = paste0(round((count / sum(count)) * 100), '%') ) 
  
res <- colorPal %>%
  left_join(res, by = 'type') %>%
          mutate(lbl = paste(type, perc , sep = ' '))

# annotate the total number of events underneath the pie chart
total_number <- res %>% 
  summarise(total = sum(count)) %>% 
  pull(total)
```

```{r}
piechart <- res %>%  
  mutate(lbl = factor(lbl, levels = c("AD 1%", "TS 11%", "MXE 0%", "RI 57%", "AF 0%", "CE 13%", "AA 3%", "AL 0%", "TE 14%"))) %>% 
  ggpie(x = 'count',
        label = 'lbl',
        color = 'white',   
        size = 0,
        lab.font = c(6,'plain','red'), 
        fill = res$color) + 
  labs(tag = str_glue('Total number of AS events: {total_number}')) +
  theme(plot.tag.position = c(0.55, 0))
```

```{r}
# the bar chart with the specific numbers
bar <- final %>%
  group_by(type) %>%
  summarise(cts = n()) %>%
  arrange(desc(cts)) %>% 
  full_join(colorPal, by = 'type')

 
barplot <- bar %>% 
  ggbarplot(x ='type', y = 'cts', 
            label = TRUE,  
            lab.size = 4,
            color = 'white', fill = 'type',
            size = 0,
            ylab = 'count',
            xlab = '',
            palette = bar$color) +
  theme(legend.position = 'none',
        axis.text=element_text(size=axis_text_size),
        axis.title.y=element_text(size = general_text_size)) 
```

```{r}
# assemble the pie and the bar together
plot_grid(piechart, barplot,
          nrow = 1, align = 'v', axis = 'b') +
  ggsave('../figs/assembled_fig1.jpg', width = 13, height = 7, dpi = 300)
```


```{r}
# how many unique genes
final %>%
  distinct(ensembl_gene_id) %>%
  nrow
```

